Improve checking version of packages
advancetoolchain/advance-toolchain pull request #2215
Opened 2021-07-01 07:36 UTC by er-1

Moved into the sources files the way to get the version of the package
upstream. This allows to follow changes between the branches of a package (like liburcu for example).

Signed-off-by: Erwan Prioul <erwan@linux.ibm.com>

2021-07-01 14:01 UTC, mscastanho requested changes
@er-1 A few questions and comments:
- I don't see any updates to `libhugetlbfs` files, even though it's version was being checked by `update_revision.sh` before.
- Missing `ATSRC_PACKAGE_UPSTREAM` for liburcu and valgrind on AT next

For the last point, I believe it's because both are pointing to the master branch, so would be ignored by the original script, right? But could you add that line commented out to those files? Just to document why they are not needed there. Something like:

```
# Not needed because file follows master branch
# ATSRC_PACKAGE_UPSTREAM= 
```

2021-07-01 14:25 UTC, er-1 commented
> @er-1 A few questions and comments:
> 
>     * I don't see any updates to `libhugetlbfs` files, even though it's version was being checked by `update_revision.sh` before.

It's because it's pointing to the master branch. The check in `update_revision.sh` was ignored.

>     * Missing `ATSRC_PACKAGE_UPSTREAM` for liburcu and valgrind on AT next
> 
> For the last point, I believe it's because both are pointing to the master branch, so would be ignored by the original script, right? 

Right.

> But could you add that line commented out to those files? Just to document why they are not needed there. Something like:
> 
> ```
> # Not needed because file follows master branch
> # ATSRC_PACKAGE_UPSTREAM= 
> ```

Good idea.

2021-07-01 15:02 UTC, mscastanho approved these changes

2021-07-02 19:57 UTC, tuliom approved these changes

2021-07-06 07:01 UTC, merged