removing failovermethod option from documentation
advancetoolchain/advance-toolchain pull request #2755
Opened 2022-03-25 20:09 UTC by fabiane-watanabe

Removing failovermethod option from documentation.

2022-03-28 19:34 UTC, mscastanho requested changes
There are other mentions to `failovermethod=priority` on `configs/14.0/release_notes/release_notes-inst.html`. Example:
https://github.com/advancetoolchain/advance-toolchain/blob/1233554a7120a6f1a9e057649e0ddb4e34d0effe/configs/14.0/release_notes/release_notes-inst.html#L77

Looks like this file is used to build the Install instructions in the release notes, so we should remove the occurrences on that file as well. Note that the corresponding files for AT 15 and AT next are symlinks that end up pointing to this one, so changing this one will change for all three versions at once, which I think is OK.

Also it would be nice to mention #2557 either in the commit message or the PR body, since it's fixing that issue.

2022-03-29 13:34 UTC, rzinsly approved these changes
LGTM

2022-03-30 07:53 UTC, er-1 approved these changes

2022-03-31 16:54 UTC, mscastanho commented
This PR is ready to go, it had passed all tests, and the changes added by the rebase are unrelated to this PR, so no need to run the tests again.

2022-03-31 16:55 UTC, merged