Prepare for AT 16.0-0 Beta1
advancetoolchain/advance-toolchain pull request #2955
Opened 2022-07-07 06:59 UTC by er-1

2022-07-07 13:20 UTC, er-1 commented
AT next, it failed while building python (P10 optimized):
```
In function ‘_bufferedreader_read_generic’,
    inlined from ‘_io__Buffered_read_impl’ at /home/tcbot/bot-worker/at/src/workdir/sources/python/Modules/_io/bufferedio.c:885:0,
    inlined from ‘_io__Buffered_read’ at /home/tcbot/bot-worker/at/src/workdir/sources/python/Modules/_io/clinic/bufferedio.c.h:169:0:
/home/tcbot/bot-worker/at/src/workdir/sources/python/Modules/_io/bufferedio.c:1695: warning: ‘memcpy’ specified bound between 9223372036854775808 and 18446744073709551613 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
 1695 |             memcpy(out + written, self->buffer + self->pos, r);
      | 
./Programs/_freeze_module importlib._bootstrap /home/tcbot/bot-worker/at/src/workdir/sources/python/Lib/importlib/_bootstrap.py Python/frozen_modules/importlib._bootstrap.h
make[1]: *** [Makefile:1201: Python/frozen_modules/importlib._bootstrap.h] Illegal instruction
```

2022-07-07 17:46 UTC, mscastanho commented
More details on the Python issue: Python 3.11 added a helper program (`_freeze_module`) to create frozen modules during the build process. The Python Makefile is not detecting `python_power10` as a cross-compilation (probably because host and target archs are the same), so it builds this file with the same flags used for the rest of the build, which in this case includes `-mcpu=power10`:
```
/home/mscastanho/AT/at16-beta1/opt/at-next-17.0-0-alpha/bin/gcc -m64 -c  -DNDEBUG -O3 -mcpu=power10 <lots-of-other-flags> 
/home/mscastanho/AT/at16-beta1/build/at17.0-0-alpha.debian-11_ppc64le_ppc64le/sources/python/Programs/_freeze_module.c
```
Naturally, when we're not building on a Power10, `_freeze_module` binary fails with `Illegal Instruction` when executed.

When cross-compiling it uses a pure-Python version of this same program, which is executed by a "build Python" interpreter (can be specified with `--with-build-python`). But again, this is not an option since the Makefile is not detecting this as a cross-compilation. This will likely require more investigation and some changes to how Python is built for AT next, so it's better suited for a separate PR.

2022-07-08 12:28 UTC, mscastanho requested changes
Found a minor typo in the commit message of `Update gdb on AT 16.0` : `gdb-12-brnahc`. See other comments below.

2022-07-08 12:28 UTC, mscastanho commented on configs/16.0/packages/libhugetlbfs/sources
> +# Copyright 2021 IBM Corporation
Looks like a spurious change.

2022-07-08 12:39 UTC, er-1 commented on configs/16.0/packages/libhugetlbfs/sources
> +# Copyright 2021 IBM Corporation
Fixed

2022-07-08 12:42 UTC, er-1 commented on configs/16.0/packages/zlib/sources
>  {
If it's ok and if the current builds pass, I'd like to add those patches in another PR just for zlib.

2022-07-08 13:06 UTC, mscastanho commented on configs/16.0/packages/zlib/sources
>  {
No problem for me. This PR is already big indeed.

2022-07-11 09:49 UTC, merged